import type { Metadata } from "next";
import { Geist, Geist_Mono, Kantumruy_Pro, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar/navbarcomponent";
import FooterComponent from "@/component/footer/FooterComponent";

const kantumruy = Kantumruy_Pro({
  subsets: ['khmer'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-kantumruy',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${kantumruy.className} antialiased`}
      >
        <Navbar />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
